#!/bin/sh 

# determine system.  Currently supported are solaris (SunOS) IRIX64, IRIX,
# and Linux.

if uname  | grep "IRIX" > /dev/null
then
        SYS=sgi10k
fi
if uname | grep "SunOS" > /dev/null
then
        SYS=solaris
fi
if uname | grep "Linux" > /dev/null
then
        SYS=linux
fi
if uname | grep "FreeBSD" > /dev/null
then
	SYS=freebsd
fi

# build script for spice3f5
# display spbuild info:

HOME=`pwd`

if [ $# -eq 1 ]
then
  SYS=$1
fi

echo " "
echo "Xyce utils CLOBBER procedure:"
echo "SYS          is set to "$SYS


# set the make program (gmake is recommended)
MAKE=gmake

echo " "

$MAKE -f $HOME/Makefile SYSTEM=$SYS clobber
